# Package level variables

LEARNING_RATE_WHILE_PLAYING = 0.0001
MIN_LEARNING_RATE_WHILE_TRAINING = 0.001
EPSILON_WHILE_TRAINING_AND_PLAYING = 0.01
MIN_EPSILON_WHILE_TRAINING = 0.05
MON_HP_REWARD = 1
MON_FAINTED_REWARD = 100
VICTORY_REWARD = 600
