# Package level variables

LEARNING_RATE_WHILE_PLAYING = 0.001
MIN_LEARNING_RATE_WHILE_TRAINING = 0.01
EPSILON_WHILE_TRAINING_AND_PLAYING = 0.005
MIN_EPSILON_WHILE_TRAINING = 0.01
SARSA_DISCOUNT_FACTOR = 0.2
MON_HP_REWARD = 0.1
MON_FAINTED_REWARD = 10
VICTORY_REWARD = 30
