name: Integration tests

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string


jobs:
  integration_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python ${{ inputs.python_version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python_version }}
          cache: 'pip'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install wheel
        run: pip install --upgrade wheel
      - name: Install requirements
        run: pip install -r ./requirements.txt --upgrade
      - name: Install development requirements
        run: pip install -r ./requirements-dev.txt --upgrade
      - name: Run tests
        run: python -m pytest -x ./tests/integration_tests