name: Integration tests

on:
  workflow_call:

env:
  python_version: '3.11'

jobs:
  integration_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Python ${{ env.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}
          cache: 'pip'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install wheel
        run: pip install --upgrade wheel
      - name: Install requirements
        run: pip install -r ./requirements.txt -r ./requirements-dev.txt
      - name: Get last showdown commit hash
        id: showdown-hash
        run: |
          cd pokemon-showdown/
          export hash=`git log -1 --pretty=format:%H`
          echo "hash=$hash" >> $GITHUB_OUTPUT
      - name: Restore server cache
        uses: actions/cache@v4
        with:
          path: pokemon-showdown/node_modules
          key: ${{ matrix.os }}-${{ steps.showdown-hash.outputs.hash }}
          restore-keys: ${{ matrix.os }}
      - name: Run server in background
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then brew install gnu-sed; export PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"; fi
          printf " &" >> ./run_server.sh
          chmod +x ./run_server.sh
          ./run_server.sh
        shell: bash
      - name: Wait for server
        run: PYTHONPATH=./ python .github/scripts/check_server.py
        shell: bash
      - name: Run tests
        run: python -m pytest -x ./tests/integration_tests