name: Tests

on:
  push:
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  platform_independent_tests:
    name: Platform independent tests
    uses: './.github/workflows/platform_independent_tests.yml'
  platform_dependent_tests:
    name: Platform dependent tests
    needs: platform_independent_tests
    uses: './.github/workflows/platform_dependent_tests.yml'
    with:
      testing: true
  code_ql_scan:
    name: CodeQL scan
    needs: platform_dependent_tests
    uses: './.github/workflows/codeql-scan.yml'
  integration_tests:
    if: github.event_name == 'pull_request'
    name: Integration tests
    needs: platform_dependent_tests
    uses: './.github/workflows/integration_tests.yml'
    with:
      python_version: '3.10'