name: Tests

on:
  push:
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - '**'

jobs:
  check_if_code_changed:
    name: Check if the codebase has changed
    runs-on: ubuntu-latest
    outputs:
      python: ${{ steps.filters.outputs.python }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check diff filters
        id: filters
        uses: dorny/paths-filter@v2
        with:
          filters: |
            python:
              - '**.py'
              - '**/requirements*.txt'
              - '**/constraints.txt'
  wait_for_previous_workflows_to_finish:
    name: Wait for previous workflows to finish
    runs-on: ubuntu-latest
    needs: check_if_code_changed
    if: ${{ needs.check_if_code_changed.outputs.python == 'true' }}
    steps:
      - name: Wait for other workflows to finish
        uses: ahmadnassri/action-workflow-queue@v1
        with:
          timeout: 4800000
          delay: 60000
  platform_independent_tests:
    name: Platform independent tests
    needs: wait_for_previous_workflows_to_finish
    uses: './.github/workflows/platform_independent_tests.yml'
  platform_dependent_tests:
    name: Platform dependent tests
    needs: platform_independent_tests
    uses: './.github/workflows/platform_dependent_tests.yml'
    with:
      testing: true
  code_ql_scan:
    name: CodeQL scan
    needs: platform_dependent_tests
    uses: './.github/workflows/codeql-scan.yml'