name: Tests
on:
  push:
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  wait_for_previous_workflows_to_finish:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for other workflows to finish
        uses: ahmadnassri/action-workflow-queue@v1
        with:
          timeout: 2400000
  platform_independent_tests:
    needs: wait_for_previous_workflows_to_finish
    uses: './.github/workflows/platform_independent_tests.yml'
  platform_dependent_tests:
    needs: platform_independent_tests
    uses: './.github/workflows/platform_dependent_tests.yml'
    with:
      testing: true
  code_ql_scan:
    needs: platform_dependent_tests
    uses: './.github/workflows/codeql-scan.yml'